# Generated by Django 4.2.8 on 2023-12-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mic_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
