# Generated by Django 4.2.8 on 2023-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mic_blog', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=254, upload_to='avatars/'),
        ),
    ]
