# Generated by Django 4.2.8 on 2023-12-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mic_blog', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
